services:
  api:
    build: .
    container_name: cryptanalysis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app   # Mount code for live reload (dev mode)
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1