[project]
name = "cryptanalysis"
version = "0.1.0"
description = ""
requires-python = ">=3.12"

dependencies = [
    "numpy>=2.3.4",
    "python-dotenv",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
